# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: N2E4OGYxNzA4NjM3ZmU2ZDRhMTNjM2RlNjVhYzdhNGEyMDgwMjk4OWYzYjQ2ZWRkYTJjZjUzOTNlMTJjYmI3MzJkNWE4YTkyZWU4MzJhMDBjYTdiZDA3ZmEzMGJhZTkwMGQ0NDQzMjNhMWU4NGE5NGI5NTE0YmRlYWNmNDcxYjk=
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    username: profileCrafter
    password:
---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    username: profileCrafter
    password:
