apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: profile-crafter
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: profile-crafter.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: profile-crafter
                port:
                  number: 80
